[package]
name = "ocl-repro"
version = "0.1.0"
authors = ["Ty Overby <ty@pre-alpha.com>"]

[[bin]]
name = "demo"
path = "./src/main.rs"

[dependencies]
# ocl = "0.12.*"
ocl = { version = "0.12.0", git = "https://github.com/cogciprocate/ocl" }
